### PR TITLE
created land_page.html

### LINKED ISSUE #25: Create the Landing Page for the Website
### Type
Advancement

### Description
Create the Landing Page for the Website using HTML, CSS, Bootstrap and JavaScript. Refer this for the [UI Wireframe](https://github.com/sameersrivastava13/Vaccine-Tracker-App/tree/main/Front-end_UI) that you would need to follow.

You will have maximum 7 Days to work on this. 

### Tools
HTML
CSS
Bootstrap
JavaScript

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?
Yes

### PR DESCRIPTION
**Pull request by dilroseR**
created landing page 
Closes #25 

**Screenshots** 

### Original     
UI for Web App

### Updated
image

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
ok @dilroseR. Before I review your PR. Please first fetch upstream and merge to sync your fork with parent repo i.e. `sameersrivastava13:main` . As I have merged few pull requests that's why your branch is few commits behind the parent branch. 
Please do it once and then will see your work.

**Comment by dilroseR** [comment]
> ok @dilroseR. Before I review your PR. Please first fetch upstream and merge to sync your fork with parent repo i.e. `sameersrivastava13:main` . As I have merged few pull requests that's why your branch is few commits behind the parent branch.
> Please do it once and then will see your work.

can you check now?

**Comment by sameersrivastava13** [comment]
> > ok @dilroseR. Before I review your PR. Please first fetch upstream and merge to sync your fork with parent repo i.e. `sameersrivastava13:main` . As I have merged few pull requests that's why your branch is few commits behind the parent branch.
> > Please do it once and then will see your work.
> 
> can you check now?

Still same. Your branch `dilroseR:dilroseR` is 26 commits behind.

**Comment by dilroseR** [comment]
> > > ok @dilroseR. Before I review your PR. Please first fetch upstream and merge to sync your fork with parent repo i.e. `sameersrivastava13:main` . As I have merged few pull requests that's why your branch is few commits behind the parent branch.
> > > Please do it once and then will see your work.
> > 
> > 
> > can you check now?
> 
> Still same. Your branch `dilroseR:dilroseR` is 26 commits behind.

WhatsApp Image 2021-07-14 at 2 13 50 PM
it is not behind and also the fetch merge option is not active as i've merged it before

**Comment by sameersrivastava13** [comment]
@dilroseR  As you can see in the image below your branch is 26 commits behind the parent repo.
We added a logo folder this morning, which is actually missing in your repository. I shared a video in the slack channel on how you can sync your GitHub fork. Please try watching that video once and if still issues are there you can DM me on slack.

Capture

**Comment by dilroseR** [comment]
> @dilroseR As you can see in the image below your branch is 26 commits behind the parent repo.
> We added a logo folder this morning, which is actually missing in your repository. I shared a video in the slack channel on how you can sync your GitHub fork. Please try watching that video once and if still issues are there you can DM me on slack.
> 
> Capture


im not getting it since logo file is there in the repo

**Comment by sameersrivastava13** [comment]
@dilroseR ok understood the problem. You have made changes to your `dilroseR:dilroseR` branch which is  26 commits behind. 
& your `dilroseR:main`  branch is even with `sameersrivastava13:main`. Now you understood what is the problem?

Or in short do one thing push your work in the `dilroseR:main`  branch of your repository and make pull request using the `dilroseR:main` branch to `sameersrivastava13:main` . No issues will be there. 

Still have doubts then ping me on slack.

**Comment by dilroseR** [comment]
> @dilroseR ok understood the problem. You have made changes to your `dilroseR:dilroseR` branch which is 26 commits behind.
> & your `dilroseR:main` branch is even with `sameersrivastava13:main`. Now you understood what is the problem?
> 
> Or in short do one thing push your work in the `dilroseR:main` branch of your repository and make pull request using the `dilroseR:main` branch to `sameersrivastava13:main` . No issues will be there.
> 
> Still have doubts then ping me on slack.

Can you check now?
ive fetch and merged with dilroseR:dilroseR

**Comment by sameersrivastava13** [comment]
> Can you check now?
> ive fetch and merged with dilroseR:dilroseR

Yes now it's okay @dilroseR. Improvements are required but still will merge this pr and later on will work on making it even more better. Just do one thing create a folder name `static` put this image folder and css file in that folder and rename the `land_page.html` to `index.html`. Just do these two things and then I'll merge it.

**Comment by dilroseR** [comment]
> > Can you check now?
> > ive fetch and merged with dilroseR:dilroseR
> 
> Yes now it's okay @dilroseR. Improvements are required but still will merge this pr and later on will work on making it even more better. Just do one thing create a folder name `static` put this image folder and css file in that folder and rename the `land_page.html` to `index.html`. Just do these two things and then I'll merge it.

done!

**Pull request merged**
