### PR TITLE
contact us page

### PR DESCRIPTION
**Pull request by kumarishalini6**
## Related Issue #46 

I have made contact up page 

Contact Form - Personal - Microsoft​ Edge 7_17_2021 01_12_02 PM

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@sameersrivastava13 please have a look on this PR

**Comment by sameersrivastava13** [comment]
> @sameersrivastava13 please have a look on this PR

@kumarishalini6  Please fix the navigation bar in the contact page. It's not responsive. Rest everything looks good.

nav

**Comment by sameersrivastava13** [comment]
@kumarishalini6 Also fetch upstream. Your branch is few commits behind.

**Comment by kumarishalini6** [comment]
> @kumarishalini6 Also fetch upstream. Your branch is few commits behind.

now  please check ,is everything ok or not

**Comment by sameersrivastava13** [comment]
> > @kumarishalini6 Also fetch upstream. Your branch is few commits behind.
> 
> now please check ,is everything ok or not

No still its 5 commits behind.

**Comment by sameersrivastava13** [comment]
> > > @kumarishalini6 Also fetch upstream. Your branch is few commits behind.
> > 
> > 
> > now please check ,is everything ok or not
> 
> No still its 5 commits behind.

@kumarishalini6 There must be an fetch and merge button. You can fetch upstream using that.

**Comment by kumarishalini6** [comment]
> > > > @kumarishalini6 Also fetch upstream. Your branch is few commits behind.
> > > 
> > > 
> > > now please check ,is everything ok or not
> > 
> > 
> > No still its 5 commits behind.
> 
> @kumarishalini6 There must be an fetch and merge button. You can fetch upstream using that.

where??

**Comment by sameersrivastava13** [comment]
@kumarishalini6 Like this it must be there in your GitHub forked repository. `Fetch upstream`

C

**Comment by kumarishalini6** [comment]
> @kumarishalini6 Like this it must be there in your GitHub forked repository. `Fetch upstream`
> 
> C

the buttons are disable but i have taken upstream by code 
now i guess everything will be ok

**Pull request merged**
