### PR TITLE
Added : custom scrollbar

### PR DESCRIPTION
**Pull request by kumarishalini6**
## Related Issue #45 

InkedVaccine Tracker - Personal - Microsoft​ Edge 7_17_2021 10_09_01 PM_LI

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
@kumarishalini6 Looks good. Please fetch upstream. @Biswa-bob has just now added a smooth scroll button to the application. Please have a look and make changes according to that. Btw the custom scroll bar is looking good.

**Comment by kumarishalini6** [comment]
> @kumarishalini6 Looks good. Please fetch upstream. @Biswa-bob has just now added a smooth scroll button to the application. Please have a look and make changes according to that. Btw the custom scroll bar is looking good.

done

**Comment by sameersrivastava13** [comment]
> > @kumarishalini6 Looks good. Please fetch upstream. @Biswa-bob has just now added a smooth scroll button to the application. Please have a look and make changes according to that. Btw the custom scroll bar is looking good.
> 
> done

Fetch upstream @kumarishalini6 .

**Comment by kumarishalini6** [comment]
> > > @kumarishalini6 Looks good. Please fetch upstream. @Biswa-bob has just now added a smooth scroll button to the application. Please have a look and make changes according to that. Btw the custom scroll bar is looking good.
> > 
> > 
> > done
> 
> Fetch upstream @kumarishalini6 .

now check it please

**Comment by sameersrivastava13** [comment]
Sorry @kumarishalini6. You need to fetch upstream again. I have just now merged few other PR's. Do it and inform me I'll merge your PR first.

**Comment by kumarishalini6** [comment]
> Sorry @kumarishalini6. You need to fetch upstream again. I have just now merged few other PR's. Do it and inform me I'll merge your PR first.

@sameersrivastava13  now check it please

**Pull request merged**
