### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by deed-pooL**
Added project maintainer information

## Related Issue

No project maintainer was present initially.

## Proposed Changes
- Added Project Maintainer Information.

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
@deed-pooL Please make the title `PROJECT MAINTAINER - Sameer Srivastava` as heading and not paragraph. Also if the image is in circular shape it would look more good I guess. What are your thoughts @Sejal2801 ?

**Comment by sameersrivastava13** [comment]
@deed-pooL Similarly you can add for mentor i.e. @Sejal2801. For this you can create a separate issue. Will provide you score for that as well.

**Comment by deed-pooL** [comment]
Okay will do the same.

**Comment by sameersrivastava13** [comment]
> Okay will do the same.

You can find @Sejal2801 Photograph from her LinkedIn account I believe. Or you can just ask her on slack to give it to you.

**Comment by Sejal2801** [comment]
> @deed-pooL Please make the title `PROJECT MAINTAINER - Sameer Srivastava` as heading and not paragraph. Also if the image is in circular shape it would look more good I guess. What are your thoughts @Sejal2801 ?

Yes this is okay

**Comment by sameersrivastava13** [comment]
@deed-pooL Updates?

**Comment by deed-pooL** [comment]
I will finish it by tonight.

**Comment by sameersrivastava13** [comment]
> I will finish it by tonight.

Updates @deed-pooL ?

**Review by deed-pooL — COMMENTED** [review]
Added the required designs.

**Comment by deed-pooL** [comment]
> > I will finish it by tonight.
> 
> Updates @deed-pooL ?

Check Now!

**Comment by sameersrivastava13** [comment]
@deed-pooL Don't you think my photograph is in oval shape and @Sejal2801 in circular shape. 😂
If both were in circular shape, it would look more good. But no issues looks good now also.

Just fetch upstream as your branch is few commits behind. Synch it and then I'll merge your PR.

**Comment by deed-pooL** [comment]
Actually your photograph was vertical and making it a circular one would
have tampered the original dimensions. In the later, there was no such case.
Yea I will do that.

**Comment by Sejal2801** [comment]
Now he has updated his profile please have a look. Now it's in circular shape. It will be easy for you now.

**Comment by deed-pooL** [comment]
I'll check it out.

**Comment by Sejal2801** [comment]
okay

**Comment by deed-pooL** [comment]
Can I create a new pull request which will have all the changes required?

**Comment by deed-pooL** [comment]
I have fetched upstream, have a look.

**Comment by sameersrivastava13** [comment]
Awesome @deed-pooL . good work.

**Comment by deed-pooL** [comment]
Awesome, thanks!

**Pull request merged**
