### PR TITLE
Img Bot Added

### PR DESCRIPTION
**Pull request by ayushsoni1010**
## Related Issue  #49 

Image bot optimization added

## Check List

- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
ok @ayushsoni1010. I am merging the PR. But I think still the images need some improvements. They are getting stretched too much. Either the quality of the images are not good or its because the size of the images are too large. Need to fix it later.

**Comment by ayushsoni1010** [comment]
Alright, thanks for merging PR :)

yeah right @sameersrivastava13
Before adding the IMG bot, the website was loading and loading again because graphics are not resized. Now, yet we have added it, somehow little, only a bit of time is taking to load graphics but not the site load as we have resolved some of the issues.
 
I think we should add a preloader that would be nice, So when a user used to open a website, it would load completely and looks pretty.
What would you say?

**Comment by sameersrivastava13** [comment]
> Alright, thanks for merging PR :)
> 
> yeah right @sameersrivastava13
> Before adding the IMG bot, the website was loading and loading again because graphics are not resized. Now, yet we have added it, somehow little, only a bit of time is taking to load graphics but not the site load as we have resolved some of the issues.
> 
> I think we should add a preloader that would be nice, So when a user used to open a website, it would load completely and looks pretty.
> What would you say?

Exactly what I was thinking @ayushsoni1010 . Pre Loader is definitely a great idea. Actually I was planning to create that issue. 😂 
Would you like to work on it? then create an issue I'll assign it to you.

**Comment by ayushsoni1010** [comment]
> > Alright, thanks for merging PR :)
> > yeah right @sameersrivastava13
> > Before adding the IMG bot, the website was loading and loading again because graphics are not resized. Now, yet we have added it, somehow little, only a bit of time is taking to load graphics but not the site load as we have resolved some of the issues.
> > I think we should add a preloader that would be nice, So when a user used to open a website, it would load completely and looks pretty.
> > What would you say?
> 
> Exactly what I was thinking @ayushsoni1010 . Pre Loader is definitely a great idea. Actually I was planning to create that issue. 😂
> Would you like to work on it? then create an issue I'll assign it to you.

Sure, @sameersrivastava13 :)

**Pull request merged**
