### PR TITLE
responsive header

### PR DESCRIPTION
**Pull request by Biswa-bob**
## Related Issue

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Proposed Changes

- change1
- change2

## Check List

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if appropriate):

Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
@Biswa-bob I don't think the navigation bar is responsive. See the image below.

Capture1

**Comment by sameersrivastava13** [comment]
@Biswa-bob If you want you can redesign the entire front end. To make it responsive. If you have a better design in mind you can apply that as well.

Also I was planning to move these two parts to 2 separate pages i.e.. `Search by pincode` will have pincode part and `Search by district `name will have the district part. 

Capture2

**Comment by Biswa-bob** [comment]
> @Biswa-bob I don't think the navigation bar is responsive. See the image below.
> 
> Capture1

Actually the header is responsive but the rest is not hence interfering .

**Comment by Biswa-bob** [comment]
> @Biswa-bob I don't think the navigation bar is responsive. See the image below.
> 
> Capture1

Actually the header is responsive but the rest is not hence interfering .

**Comment by Biswa-bob** [comment]
> @Biswa-bob If you want you can redesign the entire front end. To make it responsive. If you have a better design in mind you can apply that as well.
> 
> Also I was planning to move these two parts to 2 separate pages i.e.. `Search by pincode` will have pincode part and `Search by district `name will have the district part.
> 
> Capture2

Yes i can do it but before that i need a rough sketch of the page how you want it to look like

**Pull request closed without merging**
