### PR TITLE
added search by pin code page

### PR DESCRIPTION
**Pull request by Biswa-bob**
## Related Issue

New Page
closes issue #85 

## Proposed Changes

- Made a new  Search by pincode Page

## Check List

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if appropriate):

Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

Please review and merge it @sameersrivastava13  and @Sejal2801

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
@Biswa-bob fetch upstream. Secondly, the page isn't responsive.

**Comment by Biswa-bob** [comment]
> @Biswa-bob fetch upstream. Secondly, the page isn't responsive.

Brother wait a bit don't merge now .. am working on it

**Comment by sameersrivastava13** [comment]
> > @Biswa-bob fetch upstream. Secondly, the page isn't responsive.
> 
> Brother wait a bit don't merge now .. am working on it

Sure. make sure you fetch the changes first.

**Comment by Sejal2801** [comment]
Yes Make the page responsive :) @Biswa-bob

**Comment by sameersrivastava13** [comment]
@Biswa-bob Just fix the footer of the page and I'll merge this PR. We need to move forward. Will fix other issues later. 
Submit the PR after fetching the changes with no conflicts and I will merge it. Similarly, If you can make a page for district name, I'll assign it to you that as well.

**Comment by Biswa-bob** [comment]
brother due to some technical error the file have been deleted from my system i suppose i will have to recreate it from scratch

**Comment by sameersrivastava13** [comment]
> brother due to some technical error the file have been deleted from my system i suppose i will have to recreate it from scratch

You have GitHub with you. All your code is here only. Download all files again simple.

**Pull request closed without merging**
