### PR TITLE
Added search by district name page

### PR DESCRIPTION
**Pull request by akshay399**
## Related Issue

Add Search by district name page. (HTML+CSS).

## Check List

- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
@akshay399 Check for Uttaranchal state, no city name is there. Fix it please. 

Solution is to change Uttaranchal to Uttarakhand.

**Comment by akshay399** [comment]
> @akshay399 Check for Uttaranchal state, no city name is there. Fix it please.
> 
> Solution is to change Uttaranchal to Uttarakhand.

Done

**Comment by sameersrivastava13** [comment]
Ok great @akshay399. But you need to fetch the upstream as well. Your branch is 5 commits behind. Please do that and then I'll merge this. 

also if possible please change background of the navigation bar or remove the navigation bar completely. Will fix it later.

**Comment by sameersrivastava13** [comment]
@akshay399 still behind.

**Comment by akshay399** [comment]
> @akshay399 still behind.

where is index.html in the new updated version?  @sameersrivastava13

**Comment by sameersrivastava13** [comment]
> > @akshay399 still behind.
> 
> where is index.html in the new updated version? @sameersrivastava13

Yes. I believe the last merged PR had issues. The person might have removed that file. Wait I'll undo the last commit.

**Comment by sameersrivastava13** [comment]
@akshay399 fetch the changes for the last time and I will merge this PR.

**Comment by akshay399** [comment]
> @akshay399 fetch the changes for the last time and I will merge this PR.

done @sameersrivastava13

**Comment by sameersrivastava13** [comment]
> > @akshay399 fetch the changes for the last time and I will merge this PR.
> 
> done @sameersrivastava13

Still 5 commits behind @akshay399. Fetch the changes and I'll merge immediately.

**Comment by akshay399** [comment]
> > > @akshay399 fetch the changes for the last time and I will merge this PR.
> > 
> > 
> > done @sameersrivastava13
> 
> Still 5 commits behind @akshay399

but it is showing me that my fork is even, i'll try again
image

**Comment by sameersrivastava13** [comment]
> > > > @akshay399 fetch the changes for the last time and I will merge this PR.
> > > 
> > > 
> > > done @sameersrivastava13
> > 
> > 
> > Still 5 commits behind @akshay399
> 
> but it is showing me that my fork is even, i'll try again
> image

Show me the entire picture of the screen. You might be comparing the wrong branches.

**Pull request merged**
