### PR TITLE
Added Scroll to top Button

### LINKED ISSUE #34: Scroll to top button
Can I add a Scroll to the top button on this website?

### PR DESCRIPTION
**Pull request by anupamishra333**
closes #34

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
@anupamishra333 Ok looks good. Fetch upstream as your branch `anupamishra333:main` is one commit behind. Also keep that scroll.js file inside static folder. Static -> create `scripts` folder - > place that scroll.js file inside scripts folder.

**Comment by anupamishra333** [comment]
Ohk @sameersrivastava13 i will do that , and keep update again.

**Comment by anupamishra333** [comment]
Updated Scroll.js file into a static folder.
also added all commit.
kindly Check and add.

**Comment by sameersrivastava13** [comment]
@anupamishra333 We just now have merged another PR that has new Front end for our application. Please have a look, fetch the upstream and make changes accordingly. Will merge your PR next for sure.

**Comment by anupamishra333** [comment]
Oh Sure.  kindly make this pull open if there is a need of  Scroll to top in the New Front End . Then I will add on that. first, i make a look and get back to u.

**Comment by sameersrivastava13** [comment]
> Oh Sure. kindly make this pull open if there is a need of Scroll to top in the New Front End . Then I will add on that. first, i make a look and get back to u.

Sure @anupamishra333

**Comment by sameersrivastava13** [comment]
> Oh Sure. kindly make this pull open if there is a need of Scroll to top in the New Front End . Then I will add on that. first, i make a look and get back to u.

have a look @anupamishra333. @Biswa-bob has now completed building the front end of the application and added a scroll to top button as well but that isn't smooth. See if you can do that then go ahead.

**Comment by anupamishra333** [comment]
Is it opened ??? Button have smoothness?

**Comment by sameersrivastava13** [comment]
> Is it opened ??? Button have smoothness?

No. Are you working on it? I didn't get any updates from you @anupamishra333 .

**Comment by sameersrivastava13** [comment]
> > Is it opened ??? Button have smoothness?
> 
> No. Are you working on it?

**Comment by Biswa-bob** [comment]
> Is it opened ??? Button have smoothness?

Bro use the site yourself and decide whether you can make that scroll button better , if yes then go for it . coz the performance of a  site is enhanced by the no of people using it  and their experience with it , if you can do better please ho ahead. @anupamishra333

**Pull request closed without merging**
