### PR TITLE
Created  UI using Figma

### PR DESCRIPTION
**Pull request by dilroseR**
Closes issue #12 
@sameersrivastava13 

Made a UI for Web app using Figma
Screenshots :

UI for Web App

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
Great Work @dilroseR. Looks good to me. Later we will improve it according to the requirements.  For now its looking good according to me. Let @Sejal2801 give her response on it.

**Comment by dilroseR** [comment]
> Great Work @dilroseR. Looks good to me. Later we will improve it according to the requirements. For now its looking good according to me. Let @Sejal2801 give her response on it.

Thankyou! @sameersrivastava13

**Comment by sameersrivastava13** [comment]
> Closes issue #12
> @sameersrivastava13
> 
> Made a UI for Web app using Figma
> Screenshots :
> 


Also @dilroseR. Please sync your branch with the parent branch as just now we got few pull requests merged to avoid any conflicts. Also create a folder named `UI`  or something and keep this file in that folder. Rest everything is good.

**Comment by dilroseR** [comment]
> > Closes issue #12
> > @sameersrivastava13
> > Made a UI for Web app using Figma
> > Screenshots :
> 
> Also @dilroseR. Please sync your branch with the parent branch as just now we got few pull requests merged to avoid any conflicts. Also create a folder named `UI` or something and keep this file in that folder. Rest everything is good.

Again i need to push and make a PR right?

**Comment by sameersrivastava13** [comment]
> > > Closes issue #12
> > > @sameersrivastava13
> > > Made a UI for Web app using Figma
> > > Screenshots :
> > 
> > 
> > Also @dilroseR. Please sync your branch with the parent branch as just now we got few pull requests merged to avoid any conflicts. Also create a folder named `UI` or something and keep this file in that folder. Rest everything is good.
> 
> Again i need to push and make a PR right?

Yes you have to @dilroseR. I guess now you just have to create a folder and put this UI file in that. As I can see both branches are now even.

**Comment by sameersrivastava13** [comment]
Great @dilroseR. Now just waiting for @Sejal2801 to approve it.

**Comment by dilroseR** [comment]
> > > > Closes issue #12
> > > > @sameersrivastava13
> > > > Made a UI for Web app using Figma
> > > > Screenshots :
> > > 
> > > 
> > > Also @dilroseR. Please sync your branch with the parent branch as just now we got few pull requests merged to avoid any conflicts. Also create a folder named `UI` or something and keep this file in that folder. Rest everything is good.
> > 
> > 
> > Again i need to push and make a PR right?
> 
> Yes you have to @dilroseR. I guess now you just have to create a folder and put this UI file in that. As I can see both branches are now even.

So no PR right, i've just made a folder and pushed the changes..that's it?

**Comment by sameersrivastava13** [comment]
> > > > > Closes issue #12
> > > > > @sameersrivastava13
> > > > > Made a UI for Web app using Figma
> > > > > Screenshots :
> > > > 
> > > > 
> > > > Also @dilroseR. Please sync your branch with the parent branch as just now we got few pull requests merged to avoid any conflicts. Also create a folder named `UI` or something and keep this file in that folder. Rest everything is good.
> > > 
> > > 
> > > Again i need to push and make a PR right?
> > 
> > 
> > Yes you have to @dilroseR. I guess now you just have to create a folder and put this UI file in that. As I can see both branches are now even.
> 
> So no PR right, i've just made a folder and pushed the changes..that's it?

Yes @dilroseR. Now just waiting for @Sejal2801 to approve it. Good work.

**Comment by dilroseR** [comment]
> > > > > > Closes issue #12
> > > > > > @sameersrivastava13
> > > > > > Made a UI for Web app using Figma
> > > > > > Screenshots :
> > > > > 
> > > > > 
> > > > > Also @dilroseR. Please sync your branch with the parent branch as just now we got few pull requests merged to avoid any conflicts. Also create a folder named `UI` or something and keep this file in that folder. Rest everything is good.
> > > > 
> > > > 
> > > > Again i need to push and make a PR right?
> > > 
> > > 
> > > Yes you have to @dilroseR. I guess now you just have to create a folder and put this UI file in that. As I can see both branches are now even.
> > 
> > 
> > So no PR right, i've just made a folder and pushed the changes..that's it?
> 
> Yes @dilroseR. Now just waiting for @Sejal2801 to approve it. Good work.

👍

**Comment by Sejal2801** [comment]
Good work @dilroseR

**Pull request merged**
